name: Build Flutter Android (APK & AAB)

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'         # ถ้าต้องการ build เมื่อสร้าง tag เวอร์ชัน
  pull_request:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'   # Gradle/AGP ใหม่ใช้ JDK 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
          cache: true

      - name: Flutter Pub Get
        run: flutter pub get

      # ---------- (ตัวเลือก) Lint/Test ----------
      - name: Flutter Analyze
        run: flutter analyze
      # - name: Run Tests
      #   run: flutter test
      # -----------------------------------------

      # ---------- Debug APK (ไม่เซ็น) ----------
      - name: Build Debug APK
        run: flutter build apk --debug
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
      # -----------------------------------------

      # ---------- เตรียม keystore สำหรับ Release ----------
      - name: Decode keystore
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          mkdir -p android/keystores
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/keystores/release.keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create key.properties
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          cat > android/key.properties <<EOF
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=keystores/release.keystore
          EOF
      # -----------------------------------------------------

      # ---------- Release APK (เซ็น) ----------
      - name: Build Release APK (split per ABI)
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: flutter build apk --release --split-per-abi
      - name: Upload Release APKs
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk-split
          path: build/app/outputs/flutter-apk/*.apk
      # ---------------------------------------

      # ---------- AAB สำหรับ Play Console ----------
      - name: Build Release AAB
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: flutter build appbundle --release
      - name: Upload Release AAB
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
      # ----------------------------------------------
